/**
 * @Date: 13-04-2024
 * @author: channayousif
 * @Project: 01
 * @description:
 * This guess the number game is a short TypeScript/Node.js project that allows the user to
 *  guess the number generated by the computer. There are also several ways to alter the game,
 *  like adding more rounds or displaying the score. It’s quite simple and uses the random
 *  function to generate a number.
 */
import inquirer from "inquirer";

let random_number = 0;
let score = 0;
while(true){

//Generate random number
random_number=Math.ceil(Math.random()*10);

//take user input
const user_input = await inquirer.prompt([{
    message:"Please Guess a number from 0 to 10 (Press Q or q to quit the game):",
    name:"number",
    type:"input"
}])

//Generate result
if(user_input.number=="Q"||user_input.number=="q"){
    break;
}else if(random_number-user_input.number <5){
    score=+5;
    console.log(`you are near! your score is ${score}.`)
}else{
    score=-5;
    console.log(`you are not near! your score is ${score}.`)
};

if(score<=0){
    console.log("you loose!")
    break;
}


}